name: malachapp
description: malachapp.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.0
  google_fonts: ^4.0.4
  firebase_admin: any
  logger: ^2.0.2+1
  file_picker: ^6.0.0
  firebase_storage: ^11.3.1
  cloud_firestore: ^4.13.1
  curved_navigation_bar: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/herb1.png
     - assets/herb2.png

  
  
 

