name: malachapp
description: malachapp.



publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.0
  google_fonts: ^4.0.4
  firebase_admin: any
  logger: ^2.0.2+1
  file_picker: ^6.0.0
  firebase_storage: ^11.3.1
  cloud_firestore: ^4.13.3
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.3.0
  firebase_app_check: any
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.10
  provider: ^6.1.1
  permission_handler: ^11.3.0
  http: ^0.13.6
  flutter_secure_storage: ^9.0.0
  uuid: ^4.3.3
  intl: ^0.18.1
  googleapis_auth: ^1.4.1
  shared_preferences: ^2.2.2
  getwidget: ^4.0.0
  calendar_view: ^1.1.0
  image_picker: ^1.0.7
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  smooth_sheets: ^0.4.1

flutter_icons:
  image_path: "assets/favicon.png"
  android: true
  ios: true
  web: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
     - assets/herb1.png
     - assets/herb2.png
     - assets/zd1.jpg
     - assets/zd2.jpg
     - assets/zd3.jpg
     - assets/zd4.jpg
     - assets/zd5.jpg
     - assets/zd6.jpg
     - assets/zd7.jpg
     - assets/zd8.jpg
     - assets/zd9.jpg
     - assets/zd10.jpg
     - assets/zd11.jpg
     - assets/zd12.jpg
     - assets/favicon.png

  
  
 

